name: Deploy Worker
on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: "npm"

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Check Wrangler Version
      run: wrangler --version

    - name: Install Modules
      run: npm i wrangler@latest

    - name: Build
      run: npx wrangler build

    - name: Add Header
      run: |
        cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js
        echo -e "/*!\n  * v2ray Subscription Worker (${{ github.sha }})\n  * Licensed under GPLv3\n  */\n\n$(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

    - name: Deploy
      run: |
        sed -i "s/KV_NAME/1242fbe0d8ff45979c2ae1eb73f12850/g" wrangler.toml
        wrangler deploy --api-token ZKbTHZ2_bpL0yhg3Cf1hrm0zkP1chs5U69AZnoxV --account-id 310786a171364821d830d014acfc82d7
